# GPU-Jupyter

[GPU-Jupyter](https://github.com/iot-salzburg/gpu-jupyter) provides a GPU-accelerated JupyterLab environment with PyTorch, TensorFlow, and a rich data science toolstack for reproducible deep-learning experiments.

This notebook verifies the NVIDIA driver, CUDA compiler, and GPU access from TensorFlow and PyTorch. It also compares the execution time of the same matrix operation on the CPU and GPU.

In [1]:
!jupyter --version

Selected Jupyter core packages...
IPython          : 9.15.0
ipykernel        : 7.3.0
ipywidgets       : 8.1.5
jupyter_client   : 8.9.1
jupyter_core     : 5.9.1
jupyter_server   : 2.20.0
jupyterlab       : 4.6.1
nbclient         : 0.11.0
nbconvert        : 7.17.1
nbformat         : 5.10.4
notebook         : 7.6.0
qtconsole        : not installed
traitlets        : 5.15.1


## Test NVIDIA GPU and CUDA support

`nvidia-smi` reports the installed NVIDIA driver, detected GPU, current GPU utilization, and the newest CUDA version supported by the driver.

`nvcc --version` reports the CUDA compiler version installed inside the container. These CUDA versions do not necessarily have to be identical.

In [2]:
!nvidia-smi

Wed Jul 22 12:35:37 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.173.02             Driver Version: 580.173.02     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX PRO 4000 Blac...    On  |   00000000:A2:00.0 Off |                  Off |
| 30%   37C    P8              6W /  145W |      15MiB /  24467MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Tue_May_27_02:21:03_PDT_2025
Cuda compilation tools, release 12.9, V12.9.86
Build cuda_12.9.r12.9/compiler.36037853_0


## Test TensorFlow Installation

In [4]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "1"  # Suppress informational TensorFlow messages

import tensorflow as tf

RANDOM_SEED = 23
tf.random.set_seed(RANDOM_SEED)

print(f"TensorFlow version: {tf.__version__}")
print(f"Built with CUDA support: {tf.test.is_built_with_cuda()}")

gpus = tf.config.list_physical_devices("GPU")
print(f"Detected GPUs: {gpus}")

if not gpus:
    raise RuntimeError("No GPU detected by TensorFlow.")

# Avoid allocating all available GPU memory immediately.
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

with tf.device("/GPU:0"):
    tf_test_tensor = tf.random.uniform([2000, 256], dtype=tf.float32)
    tf_test_result = tf.reduce_sum(tf_test_tensor)

print(f"Tensor device: {tf_test_tensor.device}")
print(f"Test result: {tf_test_result.numpy():.4f}")

/opt/conda/lib/python3.13/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


TensorFlow version: 2.20.0
Built with CUDA support: True
Detected GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


W0000 00:00:1784723739.462165   13522 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
W0000 00:00:1784723739.470663   13522 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
I0000 00:00:1784723739.555376   13522 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21940 MB memory:  -> device: 0, name: NVIDIA RTX PRO 4000 Blackwell, pci bus id: 0000:a2:00.0, compute capability: 12.0


Tensor device: /job:localhost/replica:0/task:0/device:GPU:0
Test result: 255918.8906


## Test PyTorch installation

In [5]:
from __future__ import print_function

import numpy as np
import torch

RANDOM_SEED = 23
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

if not torch.cuda.is_available():
    raise RuntimeError("No GPU detected by PyTorch.")

torch.cuda.manual_seed_all(RANDOM_SEED)

print(f"CUDA runtime used by PyTorch: {torch.version.cuda}")
print(f"Detected GPUs: {torch.cuda.device_count()}")
print(f"GPU 0: {torch.cuda.get_device_name(0)}")

torch_test_tensor = torch.rand(5, 3, device="cuda")
print(f"Tensor device: {torch_test_tensor.device}")
torch_test_tensor.cpu().numpy()

PyTorch version: 2.9.1+cu128
CUDA available: True
CUDA runtime used by PyTorch: 12.8
Detected GPUs: 1
GPU 0: NVIDIA RTX PRO 4000 Blackwell
Tensor device: cuda:0


array([[0.3185915 , 0.64801234, 0.08963429],
       [0.61428875, 0.891512  , 0.9505754 ],
       [0.10498129, 0.11119322, 0.6743115 ],
       [0.6665382 , 0.99047303, 0.4364057 ],
       [0.20208815, 0.57525194, 0.44523993]], dtype=float32)

## Performance test

The following cells compare the same matrix operation using NumPy, PyTorch on the CPU, PyTorch on the GPU, and TensorFlow on the GPU. The operation calculates the projection matrix used in linear regression:

$$H = X(X^T X)^{-1}X^T$$

The resulting matrix is large, so this example primarily tests whether the numerical libraries can execute a substantial workload on the configured devices.

### 1) Numpy

In [6]:
x_numpy = np.random.rand(2000, 256)

In [7]:
%%timeit -n 3 -r 3

H_numpy = x_numpy.dot(
    np.linalg.inv(x_numpy.transpose().dot(x_numpy))
).dot(x_numpy.transpose())

18 ms ± 3.25 ms per loop (mean ± std. dev. of 3 runs, 3 loops each)


### 2) PyTorch

In [8]:
x_torch_cpu = torch.rand(2000, 256, device="cpu")
print(f"Tensor device: {x_torch_cpu.device}")

Tensor device: cpu


In [9]:
%%timeit -n 3 -r 5

H_torch_cpu = x_torch_cpu.mm(
    (x_torch_cpu.t().mm(x_torch_cpu)).inverse()
).mm(x_torch_cpu.t())

The slowest run took 6.90 times longer than the fastest. This could mean that an intermediate result is being cached.
4.79 ms ± 4.75 ms per loop (mean ± std. dev. of 5 runs, 3 loops each)


### 3) PyTorch on GPU via CUDA

In [10]:
# Create the tensor directly on the first CUDA GPU.
if torch.cuda.is_available():
    x_torch_gpu = torch.rand(
        2000,
        256,
        device=torch.device("cuda:0"),
        dtype=torch.float32,
    )
    print(f"Tensor device: {x_torch_gpu.device}")
    print(x_torch_gpu[:5, :5].cpu().numpy())

Tensor device: cuda:0
[[0.3808916  0.13049333 0.38601404 0.13550214 0.4988201 ]
 [0.5941684  0.37094864 0.4889543  0.9296491  0.19993277]
 [0.5356974  0.81206596 0.6020217  0.6340812  0.7237864 ]
 [0.48894742 0.6839051  0.8042705  0.20472726 0.2839381 ]
 [0.8101024  0.45077944 0.9265322  0.6864425  0.77618426]]


In [14]:
%%timeit -n 10 -r 7

if torch.cuda.is_available():
    # Synchronization is required for runtime tests because CUDA operations execute asynchronously.
    torch.cuda.synchronize()
    H_torch_gpu = x_torch_gpu.mm(
        (x_torch_gpu.t().mm(x_torch_gpu)).inverse()
    ).mm(x_torch_gpu.t())
    torch.cuda.synchronize()

682 μs ± 20.2 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 4) TensorFlow on GPU via CUDA

In [12]:
if gpus:
    with tf.device("/GPU:0"):
        x_tf_gpu = tf.random.uniform([2000, 256], dtype=tf.float32)

    print(f"Tensor device: {x_tf_gpu.device}")
    print(x_tf_gpu[:5, :5].numpy())

Tensor device: /job:localhost/replica:0/task:0/device:GPU:0
[[0.9438342  0.3385067  0.7677115  0.6680695  0.3649447 ]
 [0.27590752 0.59973633 0.60091686 0.69706666 0.6652031 ]
 [0.05486917 0.60015345 0.7303884  0.86384666 0.1850121 ]
 [0.25567186 0.04193914 0.43598843 0.30942154 0.5328213 ]
 [0.07237387 0.17294586 0.9945524  0.182423   0.22695827]]


In [13]:
%%timeit -n 10 -r 7

if gpus:
    with tf.device("/GPU:0"):
        H_tf_gpu = tf.matmul(
            x_tf_gpu,
            tf.linalg.solve(
                tf.matmul(tf.transpose(x_tf_gpu), x_tf_gpu),
                tf.transpose(x_tf_gpu),
            ),
        )

    # Materializing one value ensures that the asynchronous GPU work has completed.
    _ = H_tf_gpu[0, 0].numpy()

1.1 ms ± 667 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


I0000 00:00:1784723742.292391   13522 cuda_solvers.cc:175] Creating GpuSolver handles for stream 0x5d4930aff610
